version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - gosec
    - misspell
    - prealloc
    - unconvert
    - unparam

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    gosec:
      excludes:
        - G101 # false positives on variable names like "token"
    misspell:
      locale: US

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - unparam
      - path: mocks/
        linters:
          - unused
          - unparam
